# Generated by Django 3.1.12 on 2021-06-25 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Creation time stamp')),
                ('modification_timestamp', models.DateTimeField(auto_now=True, verbose_name='Modification time stamp')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('name', models.CharField(max_length=250, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('country', models.CharField(max_length=100, verbose_name='country')),
                ('logo', models.ImageField(blank=True, upload_to='comparer/institution/logo', verbose_name='logo')),
            ],
            options={
                'verbose_name': 'Institution',
                'verbose_name_plural': 'Institutions',
            },
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Creation time stamp')),
                ('modification_timestamp', models.DateTimeField(auto_now=True, verbose_name='Modification time stamp')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('kind', models.PositiveSmallIntegerField(choices=[(1, 'good'), (2, 'neutral'), (3, 'bad')], default=2, verbose_name='kind')),
                ('title', models.TextField(verbose_name='title')),
                ('content', models.TextField(verbose_name='content')),
            ],
            options={
                'verbose_name': 'Message template',
                'verbose_name_plural': 'Message templates',
            },
        ),
        migrations.CreateModel(
            name='PolicyCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Creation time stamp')),
                ('modification_timestamp', models.DateTimeField(auto_now=True, verbose_name='Modification time stamp')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('name', models.CharField(max_length=250, verbose_name='name')),
                ('max_score', models.PositiveIntegerField(default=0, verbose_name='max_score')),
            ],
            options={
                'verbose_name': 'Policy category',
                'verbose_name_plural': 'Policy categories',
            },
        ),
        migrations.CreateModel(
            name='SocialMediaLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Creation time stamp')),
                ('modification_timestamp', models.DateTimeField(auto_now=True, verbose_name='Modification time stamp')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('kind', models.PositiveSmallIntegerField(choices=[(1, 'Facebook'), (2, 'Instagram'), (3, 'Twitter'), (5, 'Another')], verbose_name='kind')),
                ('url', models.URLField(verbose_name='URL address')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_media_links', to='comparer.institution', verbose_name='institution')),
            ],
            options={
                'verbose_name': 'Social media link',
                'verbose_name_plural': 'Social media links',
            },
        ),
        migrations.CreateModel(
            name='PolicyCriterion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Creation time stamp')),
                ('modification_timestamp', models.DateTimeField(auto_now=True, verbose_name='Modification time stamp')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('name', models.CharField(max_length=250, verbose_name='name')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterions', to='comparer.policycategory', verbose_name='category')),
            ],
            options={
                'verbose_name': 'Policy criterion',
                'verbose_name_plural': 'Policy criterions',
            },
        ),
        migrations.CreateModel(
            name='InstitutionPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Creation time stamp')),
                ('modification_timestamp', models.DateTimeField(auto_now=True, verbose_name='Modification time stamp')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('link', models.URLField(blank=True, verbose_name='link')),
                ('text', models.TextField(blank=True, verbose_name='text')),
                ('comment', models.TextField(blank=True, verbose_name='comment')),
                ('score', models.IntegerField(default=0, verbose_name='score')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='comparer.policycriterion', verbose_name='policy criterion')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='comparer.institution', verbose_name='institution')),
            ],
            options={
                'verbose_name': 'Institution policy',
                'verbose_name_plural': 'Institution policies',
            },
        ),
        migrations.CreateModel(
            name='InstitutionEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Creation time stamp')),
                ('modification_timestamp', models.DateTimeField(auto_now=True, verbose_name='Modification time stamp')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('address', models.EmailField(max_length=254, verbose_name='e-mail address')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='comparer.institution', verbose_name='institution')),
            ],
            options={
                'verbose_name': 'Institution e-mail',
                'verbose_name_plural': 'Institution e-mails',
            },
        ),
    ]
