# Generated by Django 3.1.12 on 2021-07-06 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('comparer', '0003_auto_20210629_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankingBrowserPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='comparer_rankingbrowserpluginmodel', serialize=False, to='cms.cmsplugin')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.AddField(
            model_name='policycriterion',
            name='order',
            field=models.IntegerField(blank=True, default=0, verbose_name='Order'),
            preserve_default=False,
        ),
    ]
