# Generated by Django 3.1.12 on 2021-07-07 13:43

import comparer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparer', '0004_auto_20210706_1919'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policycategory',
            options={'ordering': ['order'], 'verbose_name': 'Policy category', 'verbose_name_plural': 'Policy categories'},
        ),
        migrations.AddField(
            model_name='policycategory',
            name='order',
            field=models.IntegerField(blank=True, default=0, verbose_name='Order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rankingbrowserpluginmodel',
            name='inst_col_name',
            field=models.CharField(default='Institution name', max_length=100, verbose_name='Institution column name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rankingbrowserpluginmodel',
            name='order_by',
            field=models.CharField(blank=True, help_text='Specify field names separated by comma.', max_length=250, verbose_name='order by'),
        ),
        migrations.AddField(
            model_name='rankingbrowserpluginmodel',
            name='show_categories',
            field=models.ManyToManyField(default=comparer.models.get_default_categories, related_name='browser_plugin_instances', to='comparer.PolicyCategory', verbose_name='show categories'),
        ),
    ]
