# Generated by Django 3.1.12 on 2021-07-08 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparer', '0006_policycategory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policycategory',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='slug'),
        ),
    ]
