# Generated by Django 3.1.12 on 2021-07-15 14:12

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('comparer', '0008_remove_rankingbrowserpluginmodel_show_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='logo',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='comparer/institution/logo', verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='socialmedialink',
            name='kind',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Facebook'), (2, 'Instagram'), (3, 'Twitter'), (4, 'LinkedIn'), (5, 'YouTube'), (6, 'Website'), (8, 'Another')], verbose_name='kind'),
        ),
    ]
