# Generated by Django 3.1.12 on 2021-07-20 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comparer', '0009_auto_20210715_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institutionpolicy',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='institutionpolicy',
            name='criterion',
        ),
        migrations.RemoveField(
            model_name='institutionpolicy',
            name='institution',
        ),
        migrations.CreateModel(
            name='InstitutionScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Creation time stamp')),
                ('modification_timestamp', models.DateTimeField(auto_now=True, verbose_name='Modification time stamp')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('comment', models.TextField(blank=True, verbose_name='comment')),
                ('score', models.IntegerField(default=0, verbose_name='score')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='comparer.policycriterion', verbose_name='policy criterion')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='comparer.institution', verbose_name='institution')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='institutionpolicy',
            name='score',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='comparer.institutionscore', verbose_name='score'),
        ),
    ]
