# Generated by Django 3.1.12 on 2021-07-20 19:20

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comparer', '0010_auto_20210720_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='name', unique=True, verbose_name='slug'),
        ),
    ]
