# Generated by Django 3.1.12 on 2021-07-20 19:22
from autoslug.utils import slugify
from django.db import migrations


def slug_initial_values(apps, schema_editor):
    Institution = apps.get_model('comparer', 'Institution')
    for obj in Institution.objects.all():
        obj.slug = slugify(obj.name)
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('comparer', '0011_institution_slug'),
    ]

    operations = [
        migrations.RunPython(slug_initial_values)
    ]
