# Generated by Django 3.1.12 on 2021-07-20 19:34

import autoslug.fields
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('comparer', '0012_auto_20210720_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=django.utils.timezone.now, editable=True, populate_from='name', unique=True, verbose_name='slug'),
            preserve_default=False,
        ),
    ]
