# Generated by Django 3.1.12 on 2021-08-02 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparer', '0013_auto_20210720_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagetemplate',
            name='max_score',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='maximum score'),
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='min_score',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='minimum score'),
        ),
    ]
