# Generated by Django 3.1.12 on 2021-08-04 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparer', '0014_auto_20210802_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='rankingbrowserpluginmodel',
            name='compare_btn_text',
            field=models.CharField(default='COMPARE INSTITUTIONS', max_length=100, verbose_name='compare button text'),
        ),
        migrations.AddField(
            model_name='rankingbrowserpluginmodel',
            name='popup_info',
            field=models.TextField(default='You can compare at the same time up to <counter> banks', help_text='Information text displayed beside "Compare" button. Use <counter> notation to pass selection limit value.', verbose_name='comparison popup info'),
        ),
        migrations.AddField(
            model_name='rankingbrowserpluginmodel',
            name='popup_title',
            field=models.TextField(default='Institutions comparison', verbose_name='comparison popup title'),
        ),
        migrations.AddField(
            model_name='rankingbrowserpluginmodel',
            name='selection_limit',
            field=models.PositiveSmallIntegerField(default=3, help_text='Maximal number of institutions to compare.', verbose_name='selection limit'),
        ),
        migrations.AlterField(
            model_name='rankingbrowserpluginmodel',
            name='inst_col_name',
            field=models.CharField(max_length=100, verbose_name='institution column name'),
        ),
        migrations.AlterField(
            model_name='rankingbrowserpluginmodel',
            name='order_by',
            field=models.CharField(blank=True, default='-score_total', help_text='Specify field names separated by comma.', max_length=250, verbose_name='order by'),
        ),
        migrations.AlterField(
            model_name='socialmedialink',
            name='kind',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Facebook'), (2, 'Instagram'), (3, 'Twitter'), (4, 'LinkedIn'), (5, 'YouTube'), (6, 'Website'), (7, 'Another')], verbose_name='kind'),
        ),
    ]
