# Generated by Django 3.1.12 on 2021-08-20 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparer', '0015_auto_20210804_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='policycategory',
            name='short_name',
            field=models.CharField(default='undefined', help_text='Used in ranking table as title.', max_length=20, verbose_name='short name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rankingbrowserpluginmodel',
            name='popup_info',
            field=models.TextField(default='You can compare at the same time up to <counter> institutions', help_text='Information text displayed beside "Compare" button. Use <counter> notation to pass selection limit value.', verbose_name='comparison popup info'),
        ),
    ]
