# Generated by Django 3.1.12 on 2021-08-24 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparer', '0016_auto_20210820_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='rankingbrowserpluginmodel',
            name='max_order_by',
            field=models.PositiveSmallIntegerField(default=2, help_text='Determines how many ordering options can be applied at most.', verbose_name='maximum ordering options'),
        ),
        migrations.AddField(
            model_name='rankingbrowserpluginmodel',
            name='min_order_by',
            field=models.PositiveSmallIntegerField(default=0, help_text='Determines how many ordering options has be applied at least.', verbose_name='minimum ordering options'),
        ),
        migrations.AlterField(
            model_name='rankingbrowserpluginmodel',
            name='order_by',
            field=models.CharField(blank=True, default='-score_total', help_text='Default ordering. Specify field names separated by comma.', max_length=250, verbose_name='order by'),
        ),
    ]
