# Generated by Django 3.1.12 on 2021-08-26 11:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparer', '0017_auto_20210824_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='rankingbrowserpluginmodel',
            name='neutral_threshold',
            field=models.PositiveSmallIntegerField(default=34, help_text='Percentage score threshold from which score is considered neutral.', validators=[django.core.validators.MaxValueValidator(100)], verbose_name='neutral threshold'),
        ),
        migrations.AddField(
            model_name='rankingbrowserpluginmodel',
            name='positive_threshold',
            field=models.PositiveSmallIntegerField(default=67, help_text='Percentage score threshold from which score is considered positive.', validators=[django.core.validators.MaxValueValidator(100)], verbose_name='positive threshold'),
        ),
    ]
