# Generated by Django 3.1.12 on 2021-08-31 11:44

from django.db import migrations
import markdownfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('comparer', '0019_policycriterion_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='policycriterion',
            name='descr_rendered',
            field=markdownfield.models.RenderedMarkdownField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='policycriterion',
            name='description',
            field=markdownfield.models.MarkdownField(blank=True, rendered_field='descr_rendered', verbose_name='Description'),
        ),
    ]
