# Generated by Django 3.1.12 on 2021-09-22 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparer', '0021_auto_20210914_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagetemplate',
            name='title',
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='call_to_action',
            field=models.TextField(default='Provide Call To Action message', help_text='You can use [institution_name] to insert actual name of the institution', verbose_name='Call To Action'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='content',
            field=models.TextField(help_text='You can use [institution_name] to insert actual name of the institution', verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='kind',
            field=models.PositiveSmallIntegerField(choices=[(1, 'positive'), (2, 'neutral'), (3, 'negative')], default=2, verbose_name='kind'),
        ),
    ]
