# Generated by Django 3.1.12 on 2021-09-22 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparer', '0022_auto_20210922_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagetemplate',
            name='call_to_action',
            field=models.TextField(blank=True, help_text='You can use [institution_name] to insert actual name of the institution', verbose_name='Call To Action'),
        ),
    ]
