# Generated by Django 3.1.12 on 2021-08-30 11:30

import cms.models.fields
import common.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentPlaceholder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Creation time stamp')),
                ('modification_timestamp', models.DateTimeField(auto_now=True, verbose_name='Modification time stamp')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, help_text='Description for administrator.', null=True, verbose_name='description')),
                ('placeholder', cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, slotname=common.models.content_placeholder_slotname, to='cms.placeholder', verbose_name='CMS placeholder')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
