# Generated by Django 3.1.12 on 2021-09-02 07:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_coverpluginmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='coverpluginmodel',
            name='darken',
            field=models.PositiveSmallIntegerField(default=0, help_text='Percentage value of the darkness overlay applied to the background.', validators=[django.core.validators.MaxValueValidator(100)], verbose_name='darken'),
        ),
    ]
