# Generated by Django 3.1.12 on 2021-09-07 15:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactFormPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='contact_contactformpluginmodel', serialize=False, to='cms.cmsplugin')),
                ('name_fname', models.CharField(default='Your name', max_length=100, verbose_name='name of the name field')),
                ('name_placeholder', models.CharField(default='Type your name', max_length=100, verbose_name='placeholder of the name field')),
                ('email_fname', models.CharField(default='Your e-mail', max_length=100, verbose_name='name of the e-mail field')),
                ('email_placeholder', models.CharField(default='Type your e-mail', max_length=100, verbose_name='placeholder of the e-mail field')),
                ('message_fname', models.CharField(default='Your message', max_length=100, verbose_name='name of the message field')),
                ('message_placeholder', models.CharField(default='Type your message here', max_length=100, verbose_name='placeholder of the message field')),
                ('button_text', models.CharField(default='SEND MESSAGE', max_length=100, verbose_name='submit button text')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Creation time stamp')),
                ('modification_timestamp', models.DateTimeField(auto_now=True, verbose_name='Modification time stamp')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('recipient_type', models.CharField(choices=[('TO', 'TO'), ('CC', 'CC'), ('BCC', 'BCC')], default='TO', help_text='Type of the recipient: TO - normal, CC - copy, BCC - hidden copy.', max_length=3, verbose_name='recipient type')),
                ('plugin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipients', to='contact.contactformpluginmodel', verbose_name='Contact Form Plugin')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Creation time stamp')),
                ('modification_timestamp', models.DateTimeField(auto_now=True, verbose_name='Modification time stamp')),
                ('sender_name', models.CharField(max_length=100, verbose_name='sender name')),
                ('sender_email', models.EmailField(max_length=254, verbose_name='sender e-mail')),
                ('message', models.TextField(validators=[django.core.validators.MinLengthValidator(20)], verbose_name='message')),
                ('status', models.SmallIntegerField(choices=[(1, 'pending'), (2, 'sent'), (3, 'error')], default=1, verbose_name='status')),
                ('status_msg', models.TextField(verbose_name='Status message')),
                ('recipients', models.ManyToManyField(to='contact.Recipient', verbose_name='recipients')),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
            },
        ),
    ]
