# Generated by Django 3.1.12 on 2021-09-02 14:13

import autoslug.fields
import cms.models.fields
import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import markdownfield.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Creation time stamp')),
                ('modification_timestamp', models.DateTimeField(auto_now=True, verbose_name='Modification time stamp')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=True, help_text='This value is auto generated when omitted. It will represent post name in the internet address (should consist only of letters, numbers, hyphens and have to be unique).', populate_from='title', unique=True, verbose_name='slug')),
                ('publication_date', models.DateField(default=datetime.datetime.today, verbose_name='publication date')),
                ('reading_time', models.PositiveIntegerField(blank=True, help_text='Estimated averange reading time in minutes.', null=True, verbose_name='reading time')),
                ('description', markdownfield.models.MarkdownField(blank=True, rendered_field='descr_rendered', verbose_name='Description')),
                ('descr_rendered', markdownfield.models.RenderedMarkdownField()),
                ('header_image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='common/blog_post/header_image', verbose_name='header image')),
                ('header_darken', models.PositiveSmallIntegerField(default=50, help_text='Percentage value of the darkness overlay applied to the header background image.', validators=[django.core.validators.MaxValueValidator(100)], verbose_name='header darkening')),
                ('content_placeholder', cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, slotname='post_content', to='cms.placeholder', verbose_name='CMS placeholder')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
