# Generated by Django 3.1.12 on 2021-09-03 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogIndexPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='blog_blogindexpluginmodel', serialize=False, to='cms.cmsplugin')),
                ('feat_btn_text', models.CharField(default='READ ARTICLE', help_text='Text displayed on the button of featured blog post which redirects to the post details page.', max_length=50, verbose_name='featured button text')),
                ('more_title', models.CharField(default='Read more blogposts', help_text='Title of the remaining posts section.', max_length=250, verbose_name='remaining posts title')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-publication_date'], 'verbose_name': 'Blog Post', 'verbose_name_plural': 'Blog Posts'},
        ),
    ]
